// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data_handler.proto

package gravity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushRequest struct {
	EventName            string   `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab6a9d7d4590030, []int{0}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *PushRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type PushReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushReply) Reset()         { *m = PushReply{} }
func (m *PushReply) String() string { return proto.CompactTextString(m) }
func (*PushReply) ProtoMessage()    {}
func (*PushReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab6a9d7d4590030, []int{1}
}

func (m *PushReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushReply.Unmarshal(m, b)
}
func (m *PushReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushReply.Marshal(b, m, deterministic)
}
func (m *PushReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushReply.Merge(m, src)
}
func (m *PushReply) XXX_Size() int {
	return xxx_messageInfo_PushReply.Size(m)
}
func (m *PushReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushReply proto.InternalMessageInfo

func (m *PushReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PushReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*PushRequest)(nil), "gravity.PushRequest")
	proto.RegisterType((*PushReply)(nil), "gravity.PushReply")
}

func init() { proto.RegisterFile("data_handler.proto", fileDescriptor_0ab6a9d7d4590030) }

var fileDescriptor_0ab6a9d7d4590030 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x49, 0x2c, 0x49,
	0x8c, 0xcf, 0x48, 0xcc, 0x4b, 0xc9, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x4f, 0x2f, 0x4a, 0x2c, 0xcb, 0x2c, 0xa9, 0x54, 0x72, 0xe5, 0xe2, 0x0e, 0x28, 0x2d, 0xce, 0x08,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe1, 0xe2, 0x4c, 0x2d, 0x4b, 0xcd, 0x2b, 0xf1,
	0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08, 0x08, 0x49, 0x70, 0xb1,
	0x17, 0x24, 0x56, 0xe6, 0xe4, 0x27, 0xa6, 0x48, 0x30, 0x81, 0xe5, 0x60, 0x5c, 0x25, 0x5b, 0x2e,
	0x4e, 0x88, 0x31, 0x05, 0x39, 0x95, 0x20, 0x65, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5, 0x60,
	0x23, 0x38, 0x82, 0x60, 0x5c, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xd4, 0xc4, 0xe2, 0xfc, 0x3c, 0xa8,
	0x7e, 0x28, 0xcf, 0xc8, 0x91, 0x8b, 0xdb, 0x25, 0xb1, 0x24, 0xd1, 0x03, 0xe2, 0x46, 0x21, 0x23,
	0x2e, 0x16, 0x90, 0x69, 0x42, 0x22, 0x7a, 0x50, 0x67, 0xea, 0x21, 0xb9, 0x51, 0x4a, 0x08, 0x4d,
	0xb4, 0x20, 0xa7, 0x52, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x31, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4a, 0x02, 0xd2, 0xf7, 0xee, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataHandlerClient is the client API for DataHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataHandlerClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushReply, error)
}

type dataHandlerClient struct {
	cc *grpc.ClientConn
}

func NewDataHandlerClient(cc *grpc.ClientConn) DataHandlerClient {
	return &dataHandlerClient{cc}
}

func (c *dataHandlerClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushReply, error) {
	out := new(PushReply)
	err := c.cc.Invoke(ctx, "/gravity.DataHandler/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataHandlerServer is the server API for DataHandler service.
type DataHandlerServer interface {
	Push(context.Context, *PushRequest) (*PushReply, error)
}

// UnimplementedDataHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedDataHandlerServer struct {
}

func (*UnimplementedDataHandlerServer) Push(ctx context.Context, req *PushRequest) (*PushReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}

func RegisterDataHandlerServer(s *grpc.Server, srv DataHandlerServer) {
	s.RegisterService(&_DataHandler_serviceDesc, srv)
}

func _DataHandler_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHandlerServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.DataHandler/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHandlerServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gravity.DataHandler",
	HandlerType: (*DataHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _DataHandler_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_handler.proto",
}
